name: Android CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r15c

      - name: Set HAXEPATH
        run: |
          echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV

      - name: Install Haxe dependencies
        run: |
          haxelib install lime 7.9.0 --quiet
          haxelib install hxcpp 4.2.1 --quiet
          haxelib dev extension-webm $GITHUB_WORKSPACE

      - name: Configure Android support
        run: |
          haxelib run lime setup -alias -y
          lime config ANDROID_SDK $ANDROID_HOME
          lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          lime config JAVA_HOME $JAVA_HOME_8_arm64
          lime config ANDROID_SETUP true

      - name: Rebuild Extension-WebM
        run: |
          rm -rf ./ndll
          mkdir ./ndll
          haxelib run lime rebuild hxcpp
          lime rebuild extension-webm android

      - uses: actions/upload-artifact@v4
        with:
          name: Android-NDLL
          path: ndll
          if-no-files-found: error
